### ISSUE TITLE
Japanese translation

### ISSUE THREAD

**Issue by minamorl** [wavebeem/pkmn.help#117]
I made a translation based on the official site of Pokemon
Format is:
```
EN
JA
```

```
Normal
ノーマル
Poison
どく
Bug
むし
Fire
ほのお
Electric
でんき
Dragon
ドラゴン
Fighting
かくとう
Ground
じめん
Ghost
ゴースト
Water
みず
Psychic
エスパー
Dark
あく
Flying
ひこう
Rock
いわ
Steel
はがね
Grass
くさ
Ice
こおり
Fairy
フェアリー
```

```
HP
HP
Attack
こうげき
Defense
ぼうぎょ
Sp. Atk.
とくこう
Sp. Def.
とくぼう
Speed
すばやさ
```

**Comment by minamorl** [comment]
`Total` is `合計` or `総計` i guess?

**Comment by wavebeem** [comment]
> Search by name, number, or types is 「名前・番号・タイプで検索できます」

**Comment by wavebeem** [comment]
I've added these to https://github.com/wavebeem/pkmn.help/pull/134

If you would like, I can add you to the "Special Thanks" section!

**Comment by minamorl** [comment]
Ty. add me pls!

**Comment by wavebeem** [comment]
Does this look good?

👇🏻 

### Special Thanks

-    Minamorl (Japanese translation)
-    Jansjo (testing, research)
-    Several anonymous Poké Fans

**Comment by minamorl** [comment]
lgtm. thx

**Comment by wavebeem** [comment]
This is being tracked in [Google Sheets](https://docs.google.com/spreadsheets/d/1fLL-RTowBtNqUpB5LOZ6fZvnfsuUZM8RXYHMSbil1Wo/edit#gid=1849883130) now
