### ISSUE TITLE
Light mode and dark mode

### ISSUE THREAD

**Issue by Ningyoplug** [wavebeem/pkmn.help#120]
The first time I visited this website, it was in light mode. I was recording a video and showing it on screen, and it being in light mode made it easy to see what i was doing in the video.
Now the site is in dark mode and I've found no option to turn it off. Dark mode is great at night, but during the day it makes me have a hard time seeing what's on the screen and also makes things less visible when i use it in my videos.

Could you add a way to at least switch between light and dark mode instead of always having dark mode turned on?

__

Nvm, solved. It was just my windows settings. Feel free to delete this issue, i dont think i cant do it myself

**Comment by wavebeem** [comment]
Yeah, I'll get around to it at some point. 

For now, dark mode is activated based on your browsers settings. It should follow your operating systems settings normally, but I've noticed that Chrome and Firefox have started switching pages to dark mode when you switch the browser theme to dark mode.

So if you change your browser theme back to light mode that might help until I fix this.

**Comment by Ningyoplug** [comment]
> Yeah, I'll get around to it at some point.
> 
> For now, dark mode is activated based on your browsers settings. It should follow your operating systems settings normally, but I've noticed that Chrome and Firefox have started switching pages to dark mode when you switch the browser theme to dark mode.
> 
> So if you change your browser theme back to light mode that might help until I fix this.

I use Chrome and i made sure i had all "dark mode" settings turned off, that's why I thought it was just the site- i instead realized that i actually had to go change my Windows Settings. Under Personalization, and then Colors. I changed it from Dark to Custom, and then chose to make the default mode for apps be Light, that's how I solved this.
Just saying this in case anyone else comes looking for a solution and finds this.

**Comment by wavebeem** [comment]
My plan is to add:

Auto
Light
Dark

and the default will be auto (current behavior)

I currently don't even have a settings screen, so I'll have to figure something out haha

**Comment by wavebeem** [comment]
> easy to see what i was doing in the video

Is this something you would share? I'm interested in how people are using pkmn.help

> Nvm, solved. It was just my windows settings. Feel free to delete this issue, i dont think i cant do it myself

I'll keep the issue open until I implement a theme selector :)

**Comment by wavebeem** [comment]
@Ningyoplug You can now set light or dark mode directly instead of using auto

https://www.pkmn.help/more/
