### ISSUE TITLE
Resistance coverage

### ISSUE THREAD

**Issue by swansond** [wavebeem/pkmn.help#129]
On the "Offense" tab, in addition to % weakness, you could add % of pokemon that resist all of the selected types.

**Comment by wavebeem** [comment]
It's a nice idea! Probably not something I'll work on soon, but I'll keep it in mind~

**Comment by wavebeem** [comment]
Someone else just requested the ability to view Pokémon that are "NOT WEAK" against the selected types, a slight variation on this theme.

**Comment by wavebeem** [comment]
Got another person who wants % of pkmn resistant to all selected types. Maybe I'll work on this some time next month :-) Seems like a highly requested feature.
