### ISSUE TITLE
Pokedex page jumps when tapping prev button on last page

### ISSUE THREAD

**Issue by DennisPlaysTennis** [wavebeem/pkmn.help#14]
Go to the last page of the pokedex and tap the PREV button, see page jumps

**Comment by wavebeem** [comment]
I should research good behavior in other apps with regard to this... I might just remove the bottom pagination buttons though.

**Comment by wavebeem** [comment]
It probably makes sense to just scroll back to the top after clicking these buttons, since that's probably where you want to go anyway.

**Comment by wavebeem** [comment]
Fixed
