### ISSUE TITLE
Update "Pokédex" and "Offense Pokédex Coverage" for Generation 9

### ISSUE THREAD

**Issue by tur1ngb0x** [wavebeem/pkmn.help#167]
https://pokemondb.net/pokedex/game/scarlet-violet

https://pokemondb.net/scarlet-violet/exclusive

https://pokemondb.net/pokedex/stats/gen9

**Comment by wavebeem** [comment]
well _that_ was fast lol. i'm hoping that pokeapi.co gets updated with this data soon, but i miiiight try to make a temporary update that uses both data sources combined...

the stats table in particular has _all_ the data i need for the pokedex... so i might see if i can whip something up tonight

**Comment by wavebeem** [comment]
Done! Thanks for the stats table, that was perfect.

https://www.pkmn.help/pokedex/
