### ISSUE TITLE
Bug : The auto-detect language doesn’t apply the changes to the pokemon names

### ISSUE THREAD

**Issue by yazae** [wavebeem/pkmn.help#192]
The auto-detect language doesn’t apply the changes to the pokemon names :
- The site is indeed in french, but the names of the Pokémons are still in english.
- It is solved when I set french in the setting.

Anyways, very cool work ! :)

**Comment by wavebeem** [comment]
Oops! Thanks for the bug report. This was an easy fix. If you go back to "auto-detect" it should work now :)

**Comment by yazae** [comment]
Yup, after a cache cleanse it works, awesome :)

**Comment by wavebeem** [comment]
Did you need to clear your cache? When the website updates it should force all the new code to load via service worker. Anyway glad it's working :)

*Brian Mock* ( they / them )
wavebeem.com <https://www.wavebeem.com/>

**Comment by yazae** [comment]
Yeah, I had to clear the cache, no idea why ^^

I have a lot of blockers and privacy settings thought :)
