### ISSUE TITLE
Buttons for Pokemon types are of different shapes in the "Offense" and "Defense" sections

### ISSUE THREAD

**Issue by tur1ngb0x** [wavebeem/pkmn.help#204]
The Pokemon types are enclosed in a "rectangle" box in the "Offense" section whereas they are enclosed in a "capsule" box in the "Defense" section. Is this intended?

![offense-vs-defense](https://user-images.githubusercontent.com/25666761/232047712-0ff41eea-03f1-4c9f-a4a8-5ed96ec6e95d.jpg)

**Comment by wavebeem** [comment]
![image](https://user-images.githubusercontent.com/176815/232090172-a8713d31-06dd-4a9b-88a0-2a0fcaf710ec.png)

Here's the update I just pushed. I'm gonna close this as fixed, but feel free to reply if you have additional thoughts about the matter.
