### ISSUE TITLE
Offense abilities & special moves

### ISSUE THREAD

**Issue by wavebeem** [wavebeem/pkmn.help#224]
I'm still not sure how I want to add these in to the UI, but certain abilities change type matchups, and certain moves bypass the normal type matchups. Even though Pokemon can only have one ability, I think making all of these multiple choice options would be good since the Offense page can be used to model a single attacker OR an entire team attacking, unlike the defense page where there needed to be a fully separate mode.

- [Thousand Arrows (move)](https://bulbapedia.bulbagarden.net/wiki/Thousand_Arrows_(move)) | hits Flying type for 1x
- [Tinted Lens (ability)](https://bulbapedia.bulbagarden.net/wiki/Tinted_Lens_(Ability)) | Doubles damage of any move that would hit for <1x
- [Scrappy (ability)](https://bulbapedia.bulbagarden.net/wiki/Scrappy_(Ability)) | Removes Ghost's immunity to Normal and Fighting
- [Freeze-Dry (move)](https://bulbapedia.bulbagarden.net/wiki/Freeze-Dry_(move)) | Deals 2x to Water
- [Flying Press (move)](https://bulbapedia.bulbagarden.net/wiki/Flying_Press_(move)) | Half damage from Flying and half from Fighting

**Comment by wavebeem** [comment]
Added it to the list, thanks!

**Comment by sidgn** [comment]
Also Thousand Arrows also counts under the same umbrella as Flying Press and Freeze Dry.
