### ISSUE TITLE
Only one shellos variant listed

### ISSUE THREAD

**Issue by Jeffrey-Lieske** [wavebeem/pkmn.help#228]
Only West sea shellos/gastrodon are listed

**Comment by wavebeem** [comment]
I have omitted all variants that are purely cosmetic from the Pokédex. It's fun to look at them, but they just make the Pokédex longer and interfere with my calculations about type coverage.

I would consider adding them back in in the future if I updated the logic to filter out "duplicates" for type coverage.

The main reason I did this is that Pikachu has way too many cosmetic variants and it was really annoying me.

**Comment by Jeffrey-Lieske** [comment]
That wasn't too obvious since some 'mon still show that seem like they are just form changes (indeedee and oinkologne for example).

I understand you have to draw a line somewhere.

**Comment by wavebeem** [comment]
Male/Female Indeedee has the same stat _total_ but the stat distribution is different! same thing with Oinkologne. i consider pokemon to be unique based on their stats + name + types. anything else isn't considered relevant right now.

thanks for understanding. i do miss seeing the alternate forms, so it would be cool to show them but in a less annoying way at some point!
