### ISSUE TITLE
Freeze-Dry and Scrappy

### ISSUE THREAD

**Issue by quetzalthegamer** [wavebeem/pkmn.help#231]
Just adding a suggestion for another layer of the calculator.

Freeze-Dry is an Ice-type attack that is only available to Ice-type Pokémon, and has the benefit of hitting Water-types for super effective damage.

Scrappy is an ability that allows a Pokémon to hit Ghost-type targets with Normal and Fighting-type attacks, dealing regular damage.

These could be added to the offense page for some additional useful data.

**Comment by wavebeem** [comment]
I've updated #224 so I can mark this as a duplicate. Please subscribe to notifications on the other issue if you'd like to know more :)
