### ISSUE TITLE
Defense Type-Selection Bug for Mono-Types

### ISSUE THREAD

**Issue by csrzepka** [wavebeem/pkmn.help#293]
Description: There is currently a bug with the defense calculator, if you select a type in the second type section, and then select the same type in the first section, the resulting type damage calculator will show the results as if the Pokemon had that same type twice.

Steps to Reproduce:
- Go to defense tab
- Select a type in the "Choose Second Type" section, i.e. Fire
- Select that same type in the "Chose First Type" section, i.e. Fire
- Calculator will show 4x Weakness and 0.25x Weakness as if the Pokemon had dual typing of the mono type, i.e. results for Fire-Fire Pokemon.

The second type gets disabled as an option when you select that type in the first type category, but the calculator is still remembering the second type in the calculation.

![image](https://github.com/wavebeem/pkmn.help/assets/50841767/c352a3a2-d4ba-483a-bcfb-1cc7c3ba23df)

**Comment by wavebeem** [comment]
Should be fixed now! Thanks for reporting this. I definitely checked this case in the past, but I must've broken it again at some point.
