### ISSUE TITLE
Fix broken images placeholder

### ISSUE THREAD

**Issue by wavebeem** [wavebeem/pkmn.help#303]
![image](https://github.com/user-attachments/assets/e63bf136-4d22-4373-af47-7c3055f9b607)

**Comment by Nikshinde7** [comment]
I would be happy to contribute to this! Do you guys have a placeholder in mind in case the image isn't available? 
If not I was thinking of using something similar to this.

![image](https://github.com/user-attachments/assets/e81f3a7e-7f8e-485d-8495-c6ca183054cb)

**Comment by Nikshinde7** [comment]
Alright no worries! Happy coding!!

**Comment by wavebeem** [comment]
Thanks! Feel free to comment on other issues if you're interested in working on something :)

*Sage Fennel* (they/them)
wavebeem.com** <https://www.wavebeem.com>
