### ISSUE TITLE
Feature request: Click pokemon to load types.

### ISSUE THREAD

**Issue by DeWolfRobin** [wavebeem/pkmn.help#41]
Hi,

I was just using this and I thought of a handy feature: when you search a pokemon in the Pokedex, it would be handy that when you click, the pokemon's types get loaded into either the attack or defence tab.

If you want I can create this feature and create a pull request, if you would rather do it yourself, please go ahead :)

Kind regards

**Comment by wavebeem** [comment]
maybe something like, clicking the pokemon name loads it into the defense tab, whereas clicking on an individual type takes you to the offence tab for it?  i'd definitely be interested in a PR if you don't mind a bit of potential back and forth on design

**Comment by DeWolfRobin** [comment]
I've been looking at the code but since I'm new to react and typescript I find it a bit difficult to comprehend. perhaps we can try something in the form of a detailed explanation and some code snippets that I provide and then you can implement this into the source code?

# Offensive

I have been trying to access a way to update the offensive tab's type but I can't seem to find it. my idea would be that whenever you click on the type, it updates the type in the offensive tab and switches to it.

## A simple implementation would be:

under the `makeType` function of `Dex.ts` simply add an onClick and in this function add these features:
1. Change the active type of the Offensive tab
1. Change the tab to the offensive tab

# Defensive

Do the same but for the `makePKMN` function:
1. Add an onclick on the pokemon div
1. Change the type(s) of the Defensive tab
1. Change to the Defense tab

**Comment by wavebeem** [comment]
Yeah, makes sense. I'll see when I can get around to it.

**Comment by DeWolfRobin** [comment]
in the meantime, I'll try to figure it out :)

**Comment by wavebeem** [comment]
Don't hesitate to put up a draft PR and ask for help if you'd like.

**Comment by DeWolfRobin** [comment]
## Extra feature
I just came up with an extra feature that would be handy: upon hover on the pokedex entry of a pokemon, show the offensive type matrix on the left and the deffensive type matrix on the right
