### ISSUE TITLE
Support DLC (Crown Tundra, Isle of Armor)

### ISSUE THREAD

**Issue by kurisubrooks** [wavebeem/pkmn.help#75]
A small handful of new Pokémon were added in these DLC (#891-#898), and it would be neat if they could be supported by the Pokédex feature.

The only thing to note is that there are 3 forms of Calyrex (#898) with different typings, otherwise your dex crawler should work fine with the other new Pokémon.

**Comment by wavebeem** [comment]
Thanks for the reminder! I haven't been playing the DLC so I totally forgot.

https://www.pkmn.help/pokedex?page=53

I recently upgraded my scraper. I think Calyrex is being scanned in correctly. Please let me know if you find any issues~

**Comment by kurisubrooks** [comment]
Perfect! Thank you so much.
