### ISSUE TITLE
Enhancement: Multilingual Support

### ISSUE THREAD

**Issue by dudil** [wavebeem/pkmn.help#78]
I love your project it is truly amazing and helpful!

As an enhancement I would like to add multilingual support, I will be happy to assist if that's ok.

Thanks!

**Comment by wavebeem** [comment]
Thank you for the kind words, @dudil! Do you have any ideas on how to get the translated Pokemon names, type names, and form names? I have considered adding support for languages besides English, but haven't figured out a good way to automatically obtain that data.

**Comment by dudil** [comment]
My Pleasure!

Best and simplest way (IMHO) is just to decouple the text from the actual representation by creating a i18n.json / yml file.
And populate according to the language chosen.

Another option, which will require much more work (but I'll be happy to contribute of course) is to use static web generator like [Next.js](https://nextjs.org) or [Gatsby](https://www.gatsbyjs.com) which both are for react based web apps.

WDYT?

**Comment by wavebeem** [comment]
Oh, I've implemented translatable apps before, that's not the issue. My problem is how to actual obtain the translated text.

https://github.com/wavebeem/pkmn.help/blob/master/src/data-pkmn.json

If you look at the JSON file I load, `name` would need to be translated for all 1,000+ Pokemon/forms. I would also need translated words for all 18 pokemon types.

![image](https://user-images.githubusercontent.com/176815/99190734-2bf5dc80-271d-11eb-8e14-fa5e16ece252.png)

Bulbapedia mentions several affiliate wikis in other languages, but I doubt they are as complete as Bulbapedia. Plus, each one would require custom code to scrape the data.

**Comment by wavebeem** [comment]
Given the level of manual labor involved in correlating Bulbapedia's data with other wikis, I'm not interested in pursuing this feature at this time. In the event that it becomes less labor intensive to translate Pokemon names between languages, I will happily investigate adding support for other languages.
