### ISSUE TITLE
Missing button to go from pokedex tab to defense?

### ISSUE THREAD

**Issue by 851marc** [wavebeem/pkmn.help#97]
Since the update I can't find the button that previously was there to go to Defense tab of a pokemon from the pokedex search result?

**Comment by wavebeem** [comment]
Hey Marc, thanks for filing this issue. I had to remove the Bulbapedia link since I'm using PokéAPI now instead, but perhaps I was a bit hasty in removing the Defense link too...

Let me think about how to add that feature back in without messing up the carefully redesigned layout.

**Comment by wavebeem** [comment]
Maybe a little shield icon link or something?

(Rough mockup)
![image](https://user-images.githubusercontent.com/176815/123310228-b5069a80-d4da-11eb-8d6f-19737d2ed64b.png)

**Comment by 851marc** [comment]
Yes sir that would be perfect! That shortcut is super useful! :P

**Comment by wavebeem** [comment]
While I have your attention, would an "Offense" shortcut be useful too? Like one that went to the offense screen for Fire+Flying? It would be roughly the same amount of work to add both

**Comment by 851marc** [comment]
I guess it would be a little less relevant since the pokemon types doesn't always represent it's moveset? But I mean why not maybe it could still be useful!

**Comment by wavebeem** [comment]
It could be a starting point. I usually keep a move for each type so I can take advantage of STAB bonus, but yeah I definitely wasn't sure, and thus didn't add it before

**Comment by wavebeem** [comment]
@851marc Thanks for opening the issue. The fix is live! https://www.pkmn.help/pokedex

**Comment by wavebeem** [comment]
I realized sword/shield icons for offense/defense could be confusing because of Pokemon Sword/Shield (and harder to tap/click), so I went with text and made room for them elsewhere :)

**Comment by 851marc** [comment]
This is perfect thank you for your work! <3
